<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once 'db.php';

$method = $_SERVER['REQUEST_METHOD'];
$requestPath = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';

// If Railway routes everything to this file, manually pass admin URLs through.
$normalizedPath = ltrim($requestPath, '/');
if (str_starts_with($normalizedPath, 'server/')) {
    $normalizedPath = substr($normalizedPath, 7);
}

if (str_starts_with($normalizedPath, 'admin')) {
    $adminRelative = substr($normalizedPath, strlen('admin'));
    $adminRelative = ltrim($adminRelative, '/');
    $target = $adminRelative === '' ? 'index.php' : $adminRelative;

    // Prevent traversal and only allow php files inside /server/admin.
    if (str_contains($target, '..')) {
        http_response_code(400);
        header('Content-Type: text/plain');
        echo 'Bad request';
        exit;
    }

    $targetPath = __DIR__ . '/admin/' . $target;
    if (!str_ends_with($targetPath, '.php') || !is_file($targetPath)) {
        http_response_code(404);
        header('Content-Type: text/plain');
        echo 'Not found';
        exit;
    }

    require $targetPath;
    exit;
}

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

// Handle preflight requests
if ($method === 'OPTIONS') {
    exit;
}

$action = $_GET['action'] ?? '';

switch ($action) {
    case 'get_puzzles':
        handleGetPuzzles($pdo);
        break;
    case 'submit_stats':
        handleSubmitStats($pdo);
        break;
    default:
        echo json_encode([
            'status' => 'online', 
            'message' => 'Arrow Game API',
            'endpoints' => [
                'get_puzzles' => '?action=get_puzzles&count=10',
                'submit_stats' => '?action=submit_stats'
            ]
        ]);
        break;
}

function handleGetPuzzles($pdo) {
    $count = isset($_GET['count']) ? (int)$_GET['count'] : 10;
    $count = min(max($count, 1), 50); // Limit between 1 and 50
    
    $seeds = [];
    for ($i = 0; $i < $count; $i++) {
        // Generate a random 32-bit signed integer
        $seed = mt_rand(-2147483648, 2147483647);
        $seeds[] = $seed;
        
        // Ensure seed exists in DB so we can track stats later
        // Note: In production, you might want to pre-populate this or do it asynchronously
        $stmt = $pdo->prepare("INSERT INTO puzzles (seed) VALUES (?) ON CONFLICT (seed) DO NOTHING");
        $stmt->execute([$seed]);
    }
    
    echo json_encode(['seeds' => $seeds]);
}

function handleSubmitStats($pdo) {
    $data = json_decode(file_get_contents('php://input'), true);
    $seed = isset($data['seed']) ? (int)$data['seed'] : null;
    $time = isset($data['time']) ? (float)$data['time'] : null;
    $deviceId = null;

    // Accept both snake_case and camelCase to stay backwards compatible.
    if (isset($data['device_id'])) {
        $deviceId = trim((string)$data['device_id']);
    } elseif (isset($data['deviceId'])) {
        $deviceId = trim((string)$data['deviceId']);
    }

    if ($deviceId === '') {
        $deviceId = null;
    }

    if ($seed === null || $time === null) {
        http_response_code(400);
        echo json_encode(['error' => 'Invalid data. Required: seed (int), time (float)']);
        return;
    }

    try {
        // Start transaction
        $pdo->beginTransaction();

        // 1. Ensure the puzzle exists (if it wasn't generated by get_puzzles)
        $stmt = $pdo->prepare("INSERT INTO puzzles (seed) VALUES (?) ON CONFLICT (seed) DO NOTHING");
        $stmt->execute([$seed]);

        // 2. Update puzzle averages
        $stmt = $pdo->prepare("
            UPDATE puzzles 
            SET 
                avg_time_seconds = (avg_time_seconds * completions + ?) / (completions + 1),
                completions = completions + 1 
            WHERE seed = ?
        ");
        $stmt->execute([$time, $seed]);

        // 3. Log each play for raw analytics/history.
        $stmt = $pdo->prepare("INSERT INTO play_logs (seed, completion_time, device_id) VALUES (?, ?, ?)");
        $stmt->execute([$seed, $time, $deviceId]);

        // 4. Maintain per-device aggregated stats for fast reads.
        if ($deviceId !== null) {
            $stmt = $pdo->prepare("
                INSERT INTO devices (device_id, puzzles_played, total_play_time_seconds, last_seen_at, updated_at)
                VALUES (?, 1, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                ON CONFLICT (device_id)
                DO UPDATE SET
                    puzzles_played = devices.puzzles_played + 1,
                    total_play_time_seconds = devices.total_play_time_seconds + EXCLUDED.total_play_time_seconds,
                    last_seen_at = CURRENT_TIMESTAMP,
                    updated_at = CURRENT_TIMESTAMP
            ");
            $stmt->execute([$deviceId, $time]);
        }

        $pdo->commit();
        echo json_encode(['success' => true]);
    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        http_response_code(500);
        echo json_encode(['error' => 'Failed to save stats', 'details' => $e->getMessage()]);
    }
}
