<?php
require_once 'db.php';

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

$method = $_SERVER['REQUEST_METHOD'];

// Handle preflight requests
if ($method === 'OPTIONS') {
    exit;
}

$action = $_GET['action'] ?? '';

switch ($action) {
    case 'get_puzzles':
        handleGetPuzzles($pdo);
        break;
    case 'submit_stats':
        handleSubmitStats($pdo);
        break;
    default:
        echo json_encode([
            'status' => 'online', 
            'message' => 'Arrow Game API',
            'endpoints' => [
                'get_puzzles' => '?action=get_puzzles&count=10',
                'submit_stats' => '?action=submit_stats'
            ]
        ]);
        break;
}

function handleGetPuzzles($pdo) {
    $count = isset($_GET['count']) ? (int)$_GET['count'] : 10;
    $count = min(max($count, 1), 50); // Limit between 1 and 50
    
    $seeds = [];
    for ($i = 0; $i < $count; $i++) {
        // Generate a random 32-bit signed integer
        $seed = mt_rand(-2147483648, 2147483647);
        $seeds[] = $seed;
        
        // Ensure seed exists in DB so we can track stats later
        // Note: In production, you might want to pre-populate this or do it asynchronously
        $stmt = $pdo->prepare("INSERT INTO puzzles (seed) VALUES (?) ON CONFLICT (seed) DO NOTHING");
        $stmt->execute([$seed]);
    }
    
    echo json_encode(['seeds' => $seeds]);
}

function handleSubmitStats($pdo) {
    $data = json_decode(file_get_contents('php://input'), true);
    $seed = isset($data['seed']) ? (int)$data['seed'] : null;
    $time = isset($data['time']) ? (float)$data['time'] : null;

    if ($seed === null || $time === null) {
        http_response_code(400);
        echo json_encode(['error' => 'Invalid data. Required: seed (int), time (float)']);
        return;
    }

    try {
        // Start transaction
        $pdo->beginTransaction();

        // 1. Ensure the puzzle exists (if it wasn't generated by get_puzzles)
        $stmt = $pdo->prepare("INSERT INTO puzzles (seed) VALUES (?) ON CONFLICT (seed) DO NOTHING");
        $stmt->execute([$seed]);

        // 2. Update puzzle averages
        $stmt = $pdo->prepare("
            UPDATE puzzles 
            SET 
                avg_time_seconds = (avg_time_seconds * completions + ?) / (completions + 1),
                completions = completions + 1 
            WHERE seed = ?
        ");
        $stmt->execute([$time, $seed]);

        // 3. Log the play (optional but good for future analytics)
        $stmt = $pdo->prepare("INSERT INTO play_logs (seed, completion_time) VALUES (?, ?)");
        $stmt->execute([$seed, $time]);

        $pdo->commit();
        echo json_encode(['success' => true]);
    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        http_response_code(500);
        echo json_encode(['error' => 'Failed to save stats', 'details' => $e->getMessage()]);
    }
}
